apiVersion: v1
kind: Service
metadata:
  name: { { include "chart.fullname" . } }
spec:
  type: ClusterIP
  selector:
    app: { { include "chart.name" . } }
  ports:
    - port: 80
      targetPort: 80
