apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service.name } }
spec:
  type: ClusterIP
  selector:
    app: { { include "chart.name" . } }
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
